### ISSUE TITLE
does html tidy support the main element <main>

### ISSUE THREAD

**Issue by KingJahfy** [SublimeLinter/SublimeLinter-html-tidy#21]
Getting a SublimeLinter error while using htmltidy. Error `<main> is not recognized!` no errors on other new HTML5 elements such as section or header.

Install details:

    $ tidy -v
    HTML Tidy for HTML5 (experimental) for Mac OS X https://github.com/w3c/tidy-html5/tree/c63cc39

    $ echo $PATH
    /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

**Comment by skj3gg** [comment]
This is a problem with [html-tidy5](https://github.com/w3c/tidy-html5) which seems abandonware (at time of writing). There is a [PR](https://github.com/w3c/tidy-html5/pull/98) from a year and a half ago, you could clone the source, add the patch and recompile the binary.

Closing because there is no issue for SL
