### ISSUE TITLE
Error at the end of file

### ISSUE THREAD

**Issue by Nicolai6120** [SublimeLinter/SublimeLinter-html-tidy#26]
I have php file.
![error](https://cloud.githubusercontent.com/assets/6821061/6122632/ce22b1ca-b10f-11e4-8f84-2bf391920cef.png)
At the end of file html-tidy show error. I can't ignore_match this, because this error not showing in the list of errors (show all errors), and i don't know what this error mean. My favorite fuction of linter "Show errors on save" not working right with it:-(

UPD: I`m sorry, that is my mistake. When i disable "Make Warnings Passive" it's OK.

**Comment by Aedx** [comment]
Does it show the error name in status bar (at the bottom left hand corner)? For example, it tells me that there is a missing `<title>` element (this is because html-tidy is intended for vanilla HTML, and has limited PHP support). You may find it useful to disable the html-tidy SublimeLinter plugin for your PHP files, and instead use the recommended [PHP SublimeLinter plugin](https://github.com/SublimeLinter/SublimeLinter-php).

You can toggle the html-tidy SublimeLinter plugin by following steps:

1. Open the Command Palette (<kbd>Ctrl+Shift+P</kbd> by default on Linux and Windows, replace <kbd>Ctrl</kbd> with <kbd>Cmd</kbd> for OS X).
2. Search for `SublimeLinter: Toggle Linter`, and either select the option with your mouse or navigate to it with your arrow keys and press enter.
3. From the menu which now appears, find the option named `htmltidy` and either select it with your mouse or navigate to it with your arrow keys and press enter.

**Comment by Aedx** [comment]
No updates in over a month (and the issue was supposedly a mistake), so this is being closed.
