### ISSUE TITLE
Package not available?

### ISSUE THREAD

**Issue by becskr** [SublimeLinter/SublimeLinter-html-tidy#37]
When I search the Package Installer in Sublime 3 I can't see it any more?

**Comment by grotewold** [comment]
Hi @becskr, sorry you're having problems. Could you already have it installed? If Package Control finds it in a couple places it won't be displayed in the Command Palette when searching. Check your Packages, Installed_Packages, and the Package Control settings file for SublimeLinter-html-tidy. Hope this helps!

**Comment by becskr** [comment]
I got it working eventually, although it only seems to highlight issues, not fix them. And I can't seem to make sort-attributes work at all. 
`"args": [
                    "--sort-attributes",
                    "alpha"
                ],`
I'm a new Sublime user so not great with it.

**Comment by grotewold** [comment]
Well happy to hear it's working... sort of :frowning: 

Ok, so I just noticed #36 as well. Which is the same problem as your sort-attributes options issue. So I'll have to look at that. As for not fixing issues found with html-tidy, thats because this product only does the highlighting. You'll still want to use the tidy command to do the "tidying". Maybe someday SL will support things like auto correcting but right now, it's out of scope of the project.

**Comment by becskr** [comment]
Thanks for your reply - I discovered shortly afterwards about the linters not "executing" as it were. There's no point really getting "sort attributes" to work unless the it's executed I think, otherwise you'll end up with almost every line of code being marked up. When you say use the tidy command, I assume you mean through Terminal/Command Line?

**Comment by braver** [comment]
> When you say use the tidy command, I assume you mean through Terminal/Command Line?

Yes, SL is just for linting, not for fixing. For that you’ll have to run the command from outside Sublime, or via a build system.
