### ISSUE TITLE
How to work with Ionic/Angular custom components/attributes?

### ISSUE THREAD

**Issue by arthurduarte1** [SublimeLinter/SublimeLinter-html-tidy#58]
Check those exemples out:

![image](https://user-images.githubusercontent.com/1207725/109185789-17d76780-776f-11eb-99d9-7a94ea98fc4d.png)
![image](https://user-images.githubusercontent.com/1207725/109185898-3178af00-776f-11eb-9cf9-bc1a39299cd9.png)

Thanks in advance,
Arthur Duarte.

**Comment by kaste** [comment]
This is generally the wrong repo to ask because we're only providing a small bridge/adapter between tidy and SublimeLinter.

You need to write a config file for this to work iirc.  Also see #47.  I would probably ask the Ionic people which linter they prefer with their framework.  Iirc you can teach tidy to accept custom elements but am not sure about the template-like custom attributes.

**Comment by arthurduarte1** [comment]
Got it.
Thanks for the instructions.
Take care, @kaste .
